import {formatText} from './math.js';
import {checkAnswer} from './checks.js';
import {readingHTML,bindReading,examFocusHTML} from './reading.js';
import {experimentHTML,bindExperiment} from './reading-experiments.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const main=document.querySelector('main');let data,active;const attempts=new Map();
function sourceHTML(source){if(!source)return'';return `<details class="source"><summary>Original exam part · ${esc(source.label)}</summary><p>${formatText(source.note)}</p>${(source.givens??[]).map(s=>`<p><strong>Given information:</strong> ${formatText(s)}</p>`).join('')}${(source.context_assets??[]).map(a=>`<img src="${esc(a)}" alt="Original question setup and diagram" loading="lazy">`).join('')}${(source.assets??[]).map(a=>`<img src="${esc(a)}" alt="Original question part ${esc(source.part)}" loading="lazy">`).join('')}<a href="${esc(source.url)}" target="_blank" rel="noopener">Open original paper ↗</a>${source.mark_url?`<a href="${esc(source.mark_url)}" target="_blank" rel="noopener">Original mark scheme ↗</a>`:''}<small>${esc(source.suitability)}</small></details>`;}
function answerSource(source){if(source?.answer_text)return `<p class="source-key">Original marking evidence: ${formatText(source.answer_text)} <a href="${esc(source.mark_url)}" target="_blank" rel="noopener">Open source key ↗</a></p>`;return source?.answer_assets?.length?`<details class="source"><summary>See the original mark-scheme extract</summary>${source.answer_assets.map(a=>`<img src="${esc(a)}" alt="Original mark-scheme extract for this part" loading="lazy">`).join('')}</details>`:'';}
function activityHTML(a,mode='practice'){
 const attempted=attempts.get(a.id),value=attempted?.value??'';
 const fields=a.type==='choice'?`<fieldset><legend>Choose one answer</legend>${a.options.map((o,i)=>`<label class="choice"><input type="radio" name="${esc(a.id)}" value="${i}" ${String(value)===String(i)?'checked':''}><span>${formatText(o)}</span></label>`).join('')}</fieldset>`:a.type==='numeric'?`<div class="entry"><label>Your answer<input name="answer" inputmode="decimal" autocomplete="off" value="${esc(value)}"></label>${a.unit?`<label>Unit<select name="unit"><option value="">Choose unit</option>${a.units.map(u=>`<option value="${esc(u)}" ${u===attempted?.unit?'selected':''}>${esc(u)}</option>`).join('')}</select></label>`:''}</div>`:`<label class="sr-only" for="answer-${esc(a.id)}">Write your explanation</label><textarea id="answer-${esc(a.id)}" name="answer" placeholder="Write your reasoning before opening the checklist.">${esc(value)}</textarea>`;
 return `<article class="activity" data-id="${esc(a.id)}"><p class="eyebrow">${esc(a.stage??'Independent practice')}</p><h4>${esc(a.title??'Your turn')}</h4><p class="origin">${esc(a.origin??'Original exam-style practice')}</p><p class="prompt">${formatText(a.prompt)}</p>${sourceHTML(a.source)}<form data-activity="${esc(a.id)}" data-mode="${mode}">${fields}${mode==='assessment'?'':a.hints?.length?`<details class="hint"><summary>Get a hint</summary><ol>${a.hints.map(h=>`<li>${formatText(h)}</li>`).join('')}</ol></details>`:''}${mode==='assessment'?'':`<button class="primary" type="submit">${a.type==='explain'?'Compare with the marking checklist':'Check answer'}</button>`}<div class="feedback-slot" aria-live="polite"></div></form></article>`;
}
function showFeedback(form,a){
 const fd=new FormData(form);const value=a.type==='choice'?fd.get(a.id):fd.get('answer'),unit=fd.get('unit');
 const slot=form.querySelector('.feedback-slot');attempts.set(a.id,{value,unit});
 if(a.type==='explain'){
  if(!String(value??'').trim()){slot.innerHTML='<div class="feedback error">Write an explanation first. A short attempt is enough to start.</div>';return;}
  slot.innerHTML=`<div class="feedback"><strong>Mark your explanation</strong><p>${formatText(a.model)}</p>${a.rubric.map((r,i)=>`<label class="rubric"><input type="checkbox" data-rubric="${i}">${formatText(r)}</label>`).join('')}<p class="rubric-score">Self-assessment: 0 of ${a.rubric.length} points identified. This is not an automatically awarded exam mark.</p>${answerSource(a.source)}</div>`;
  slot.querySelectorAll('[data-rubric]').forEach(c=>c.addEventListener('change',()=>{slot.querySelector('.rubric-score').textContent=`Self-assessment: ${slot.querySelectorAll('[data-rubric]:checked').length} of ${a.rubric.length} points identified. This is not an automatically awarded exam mark.`;}));return;
 }
 const r=checkAnswer(a,value,unit);attempts.set(a.id,{value,unit,...r});
 slot.innerHTML=`<div class="feedback ${r.correct?'':'error'}"><strong>${r.valid?(r.correct?'Correct '+(a.type==='numeric'?'numerical answer':'choice'):'Not yet'):'Before checking'}</strong><p>${formatText(r.message)}</p>${r.correct&&a.type==='numeric'?'<p>Check your method against the solution; this checks the final value and unit only.</p>':''}${r.valid?`<details><summary>Show the explained solution</summary><p>${formatText(a.solution??a.explanation)}</p>${answerSource(a.source)}</details>`:''}</div>`;
}
function wireActivities(activities){main.querySelectorAll('form[data-activity]').forEach(form=>{const a=activities.find(x=>x.id===form.dataset.activity);form.addEventListener('submit',e=>{e.preventDefault();if(form.dataset.mode!=='assessment')showFeedback(form,a);});form.addEventListener('input',e=>{if(e.target.matches('[data-rubric]'))return;const fd=new FormData(form);attempts.set(a.id,{value:a.type==='choice'?fd.get(a.id):fd.get('answer'),unit:fd.get('unit')});form.querySelector('.feedback-slot').innerHTML='';const summary=main.querySelector('#assessment-summary');if(summary)summary.textContent='Answers changed. Finish the attempt again to update your review.';});});}
function nav(){document.querySelector('#units').innerHTML=data.lessons.map((l,i)=>`<a href="#${esc(l.id)}" ${l===active&&!['#assessment','#combined'].includes(location.hash)?'aria-current="page"':''}><span>${String(i+1).padStart(2,'0')}</span>${esc(l.title)}</a>`).join('')+`<a href="#combined" ${location.hash==='#combined'?'aria-current="page"':''}><span>↗</span>Combined exam practice</a><a href="#assessment" ${location.hash==='#assessment'?'aria-current="page"':''}><span>✓</span>Bring it together</a>`;}
function render(){const id=decodeURIComponent(location.hash.slice(1));active=data.lessons.find(l=>l.id===id)??data.lessons[0];nav();if(id==='assessment'){renderAssessment();return;}if(id==='combined'){renderCombined();return;}
 const activities=[active.guided,...active.independent];
 main.innerHTML=`<p class="eyebrow">Learn · ${esc(active.code??'B.2')}</p><h2>${esc(active.title)}</h2><p class="lead">${formatText(active.goal)}</p><div class="lesson-meta"><span class="pill">SL &amp; HL</span><span>${active.reading_minutes} min read + practice</span></div>${active.bridge?`<details class="bridge"><summary>Before you start · ${esc(active.bridge.title)}</summary><p>${formatText(active.bridge.text)}</p></details>`:''}${readingHTML(active)}${experimentHTML(active.id)}${examFocusHTML(active)}<section class="worked"><p class="eyebrow">Worked example</p><h3>${formatText(active.worked.title)}</h3><p class="origin">${formatText(active.worked.origin??'Original teaching example')}</p><p>${formatText(active.worked.prompt)}</p>${sourceHTML(active.worked.source)}<ol>${active.worked.steps.map(x=>`<li>${formatText(x)}</li>`).join('')}</ol><p class="answer-box">${formatText(active.worked.answer)}</p>${answerSource(active.worked.source)}</section><section class="section"><h3>Put the idea to work</h3><p class="lead">Start with support, then try a fresh question on your own.</p><div class="practice">${activities.map(a=>activityHTML(a)).join('')}</div></section><div class="next-lesson"><a href="#${data.lessons[data.lessons.indexOf(active)+1]?.id??'combined'}">${data.lessons[data.lessons.indexOf(active)+1]?'Next: '+esc(data.lessons[data.lessons.indexOf(active)+1].title):'Combined exam practice'} →</a><a href="#lesson">Back to top</a></div>`;
 bindReading(main);bindExperiment(main,active.id);wireActivities(activities);}
function renderCombined(){const acts=data.combined;main.innerHTML=`<p class="eyebrow">Combine the concepts</p><h2>Work through exam questions.</h2><p class="lead">Use the concepts together, with optional support. You may recognise parts from the focused lessons; now calculate the earlier results yourself.</p><div class="practice">${acts.map(a=>activityHTML({...a,stage:'Combined practice'})).join('')}</div><div class="next-lesson"><a href="#assessment">Next: choose the method yourself →</a></div>`;wireActivities(acts);}
function renderAssessment(){const acts=data.assessment;main.innerHTML=`<p class="eyebrow">Bring it together</p><h2>Choose the physics yourself.</h2><p class="lead">Try these unfamiliar questions without lesson labels or hints. Use your data booklet and calculator.</p><p class="assessment-note">Work through the complete set before revealing feedback. Numerical answers are checked automatically; written reasoning is self-marked. This practice set is not a predicted paper.</p><div class="practice">${acts.map((a,i)=>activityHTML({...a,title:'Question '+(i+1),stage:'Final practice'},'assessment')).join('')}</div><button class="primary" id="mark-assessment">Finish attempt &amp; review answers</button><p id="assessment-summary" role="status"></p>`;wireActivities(acts);main.querySelector('#mark-assessment').onclick=()=>{let incomplete=0;main.querySelectorAll('form').forEach(f=>{const a=acts.find(x=>x.id===f.dataset.activity);showFeedback(f,a);if(!String(attempts.get(a.id)?.value??'').trim())incomplete++;});const auto=acts.filter(a=>a.type!=='explain');const correct=auto.filter(a=>attempts.get(a.id)?.correct).length;main.querySelector('#assessment-summary').textContent=`${correct} of ${auto.length} numerical or multiple-choice answers correct. ${incomplete?incomplete+' unanswered question(s). ':''}Use the checklists to assess written explanations; no overall exam grade is assigned.`;};}
async function start(){try{const response=await fetch('catalog.json');if(!response.ok)throw new Error('catalog unavailable');data=await response.json();render();window.addEventListener('hashchange',()=>{if(location.hash==='#lesson'){main.focus();return;}render();main.focus();});document.querySelector('#reset').onclick=()=>{attempts.clear();render();};}catch(error){console.error('Lesson render failed',error);main.innerHTML='<h2>The lesson could not load.</h2><p>Please refresh the page, or return to the <a href="../../">question library</a>.</p>';}}
start();
