import {findPractice,topicCounts,findArchive} from './practice-search.js';
import {practiceCard,esc} from './practice-render.js';
import {progressPosition} from './practice-state.js';
const $=id=>document.getElementById(id),selected=new Set();
let data,matches=[],shown=0,activeView='selection',selectionScroll=0,progressQueued=false;
const filters=()=>({topics:[...selected],from:$('year-from').value,to:$('year-to').value,paper:$('paper').value,variant:$('variant').value,keyword:$('keyword').value});
const announce=text=>{$('announcer').textContent=text;};
function updateSelection(){
 if(!data)return;const f=filters(),counts=topicCounts(data,f),results=findPractice(data,f),n=results.length,parts=results.reduce((n,r)=>n+r.targets.length,0),invalid=Number(f.from)>Number(f.to);
 document.querySelectorAll('[data-subtopic]').forEach(input=>{input.checked=selected.has(input.dataset.subtopic);input.closest('label').querySelector('.sub-count').textContent=counts[input.dataset.subtopic].toLocaleString();});
 document.querySelectorAll('[data-topic]').forEach(input=>{const ids=data.subtopics.filter(s=>s.topic_id===input.dataset.topic).map(s=>s.id);input.checked=ids.every(id=>selected.has(id));input.indeterminate=!input.checked&&ids.some(id=>selected.has(id));input.closest('summary').querySelector('.topic-count').textContent=findPractice(data,{...f,topics:ids}).reduce((sum,r)=>sum+r.targets.length,0).toLocaleString();});
 $('selection-count').textContent=invalid?'Check your year range':!selected.size?'Choose a topic to begin':n?`${n.toLocaleString()} ${n===1?'question':'questions'} ready`:'No questions match these choices';
 $('selection-note').textContent=invalid?'The starting year must be no later than the ending year.':n?`${parts.toLocaleString()} question ${parts===1?'part':'parts'} · Hints, key notes and answers included.`:'Try another topic, a wider year range or a shorter keyword.';$('search-button').disabled=!n||invalid;
 try{localStorage.setItem('maths-higher-choices-v1',JSON.stringify(f));}catch{}
}
function renderTopics(){
 $('topic-tree').innerHTML=data.topics.map((t,i)=>`<details class="topic-group" ${i===0?'open':''}><summary><label class="topic-label"><input type="checkbox" data-topic="${esc(t.id)}"><span>${esc(t.name)}</span></label><span class="topic-count"></span></summary><div class="subtopics">${data.subtopics.filter(s=>s.topic_id===t.id).map(s=>`<label class="subtopic-label"><input type="checkbox" data-subtopic="${esc(s.id)}"><span class="subtopic-name">${esc(s.name)}</span><span class="sub-count"></span></label>`).join('')}</div></details>`).join('');
 $('topic-tree').addEventListener('change',e=>{const input=e.target;if(!input.matches('input'))return;const ids=input.dataset.subtopic?[input.dataset.subtopic]:data.subtopics.filter(s=>s.topic_id===input.dataset.topic).map(s=>s.id);ids.forEach(id=>input.checked?selected.add(id):selected.delete(id));updateSelection();});$('topic-tree').querySelectorAll('summary label').forEach(l=>l.addEventListener('click',e=>e.stopPropagation()));
}
function updateProgress(){progressQueued=false;if(activeView!=='practice')return;const tops=[...$('question-list').children].map(el=>el.getBoundingClientRect().top),readingLine=document.querySelector('.practice-toolbar').getBoundingClientRect().bottom+50;const {current,total,remaining}=progressPosition(tops,matches.length,readingLine);$('progress-label').textContent=`Question ${current} of ${total.toLocaleString()}`;$('remaining-label').textContent=`${remaining.toLocaleString()} remaining`;$('practice-progress').max=total||1;$('practice-progress').value=current;}
function queueProgress(){if(!progressQueued){progressQueued=true;requestAnimationFrame(updateProgress);}}
function showMore(){const next=matches.slice(shown,shown+12);$('question-list').insertAdjacentHTML('beforeend',next.map((r,i)=>practiceCard(r,shown+i,data)).join(''));shown+=next.length;$('load-more').hidden=shown>=matches.length;$('set-end').hidden=shown<matches.length;queueProgress();}
function setView(view,focus=true){if(view==='practice'&&!matches.length)view='selection';if(activeView==='selection'&&view!=='selection')selectionScroll=window.scrollY;activeView=view;['home','notes','selection','practice','papers'].forEach(v=>$(v+'-view').hidden=v!==view);for(const [id,on] of [['practice-nav',['selection','practice'].includes(view)],['papers-nav',view==='papers']]){if(on)$(id).setAttribute('aria-current','page');else $(id).removeAttribute('aria-current');}if(view==='papers')renderArchive();window.dispatchEvent(new CustomEvent('neumeris:subject-view',{detail:view==='selection'?'choose':view}));if(focus){window.scrollTo(0,view==='selection'?selectionScroll:0);$(view==='selection'?'selection-title':view==='papers'?'papers-title':view==='home'?'home-title':view==='notes'?'notes-title':'practice-title').focus({preventScroll:true});}queueProgress();}
function navigate(hash){if(location.hash!==hash)history.pushState(null,'',hash);setView(hash==='#papers'?'papers':hash==='#practice'?'practice':'selection');}
function startPractice(){matches=findPractice(data,filters());if(!matches.length)return;shown=0;$('question-list').innerHTML='';const names=data.subtopics.filter(s=>selected.has(s.id)).map(s=>s.name);$('practice-selection').textContent=`${names.length>3?`${names.length} topics`:names.join(' · ')} · ${$('year-from').value}–${$('year-to').value}`;showMore();navigate('#practice');announce(`${matches.length} practice questions ready.`);}
function renderArchive(){if(!data)return;const found=findArchive(data,{from:$('archive-from').value,to:$('archive-to').value,paper:$('archive-paper').value});$('archive-count').textContent=`${found.length} Higher papers`;$('paper-list').innerHTML=found.map(s=>`<article class="paper-card"><p class="paper-year">${s.year}</p><h2>${esc(s.session)} · Paper ${esc(s.paper)}</h2><p class="field-help">${esc(s.qualification)} · Higher${s.regional?' · Regional variant':''}</p><div class="source-links"><a href="${esc(s.url)}" target="_blank" rel="noopener">Question paper ↗</a>${s.mark_scheme?`<a href="${esc(s.mark_scheme.url)}#page=${s.mark_scheme.start_page||1}" target="_blank" rel="noopener">Mark scheme ↗</a>`:'<span>Mark scheme unavailable</span>'}</div></article>`).join('')||'<p class="empty-state">No papers in this range. Try adjusting the years.</p>';}
async function load(){try{
 $('load-error').hidden=true;const response=await fetch('practice-library.json');if(!response.ok)throw new Error('Please check your connection and try again.');data=await response.json();const years=[...new Set(Object.values(data.sources).map(s=>s.year))].sort((a,b)=>a-b),options=years.map(y=>`<option>${y}</option>`).join('');['year-from','year-to','archive-from','archive-to'].forEach(id=>{$(id).innerHTML=options;$(id).disabled=false;});$('year-to').value=years.at(-1);$('archive-to').value=years.at(-1);
 try{const saved=JSON.parse(localStorage.getItem('maths-higher-choices-v1'));if(saved){(saved.topics||[]).forEach(t=>{if(data.subtopics.some(s=>s.id===t))selected.add(t);});if(years.includes(Number(saved.from)))$('year-from').value=saved.from;if(years.includes(Number(saved.to)))$('year-to').value=saved.to;for(const [id,key] of [['paper','paper'],['variant','variant'],['keyword','keyword']])if(saved[key])$(id).value=saved[key];}}catch{}
 renderTopics();updateSelection();$('coverage-note').textContent=`${data.coverage.parts.toLocaleString()} supported question parts in topical practice. The Past papers tab retains all ${findArchive(data).length} original Mathematics A Higher papers. ${data.coverage.cross_board_parts?`${data.coverage.cross_board_parts} additional parts from other boards have been reviewed for this syllabus.`:"Parts still awaiting a topic or answer check remain available in the full papers."}`;applyTopicRoute();setView(viewFromHash(),false);
 }catch(error){$('error-message').textContent=error.message||'Please try again.';$('load-error').hidden=false;setView('selection',false);}}
$('search-form').addEventListener('submit',e=>{e.preventDefault();if(data)startPractice();});$('change-questions').addEventListener('click',()=>navigate('#choose'));$('practice-nav').addEventListener('click',e=>{e.preventDefault();navigate('#choose');});$('papers-nav').addEventListener('click',e=>{e.preventDefault();navigate('#papers');});
$('all-topics').addEventListener('click',()=>{data?.subtopics.forEach(s=>selected.add(s.id));updateSelection();});$('clear-topics').addEventListener('click',()=>{selected.clear();updateSelection();});$('reset-filters').addEventListener('click',()=>{selected.clear();for(const id of ['paper','variant'])$(id).value='all';$('keyword').value='';$('year-from').selectedIndex=0;$('year-to').selectedIndex=$('year-to').options.length-1;updateSelection();});
for(const id of ['year-from','year-to','paper','variant'])$(id).addEventListener('change',updateSelection);$('keyword').addEventListener('input',updateSelection);for(const id of ['archive-from','archive-to','archive-paper'])$(id).addEventListener('change',renderArchive);
$('load-more').addEventListener('click',()=>{showMore();announce(`Showing ${shown} of ${matches.length} questions.`);});$('question-list').addEventListener('click',e=>{const button=e.target.closest('.help-toggle');if(!button)return;const panel=$(button.getAttribute('aria-controls'));panel.hidden=!panel.hidden;button.setAttribute('aria-expanded',String(!panel.hidden));queueProgress();});
$('question-list').addEventListener('load',queueProgress,true);window.addEventListener('scroll',queueProgress,{passive:true});window.addEventListener('resize',queueProgress);new ResizeObserver(queueProgress).observe($('question-list'));window.addEventListener('popstate',()=>setView(viewFromHash()));window.addEventListener('hashchange',()=>setView(viewFromHash()));$('retry-load').addEventListener('click',load);export const ready=load();

function viewFromHash(){const name=location.hash.slice(1).split('?')[0];return ({home:'home',notes:'notes',choose:'selection',practice:'practice',papers:'papers'})[name]||'home';}
function applyTopicRoute(){if(!data)return;const topic=new URLSearchParams(location.hash.split('?')[1]||'').get('topic');if(topic&&data.topics.some(t=>t.id===topic)){selected.clear();data.subtopics.filter(s=>s.topic_id===topic).forEach(s=>selected.add(s.id));updateSelection();document.querySelector('[data-topic="'+CSS.escape(topic)+'"]')?.closest('details').setAttribute('open','');}}
addEventListener('hashchange',applyTopicRoute);
