export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const partLabel=v=>String(v).split('.').map(x=>'('+x+')').join('');
export function images(assets,label,eager=false){return `<div class="part-excerpt">${assets.map((a,i)=>a.crop?`<div class="excerpt-window" style="aspect-ratio:${a.crop[2]}/${a.crop[3]}"><img src="${esc(a.path)}" width="${a.width}" height="${a.height}" loading="${eager&&i===0?'eager':'lazy'}" alt="${esc(label)}" style="width:${a.width/a.crop[2]*100}%;left:${-a.crop[0]/a.crop[2]*100}%;top:${-a.crop[1]/a.crop[3]*100}%">${a.mask?`<span aria-hidden="true" style="position:absolute;background:white;left:${a.mask[0]}%;top:${a.mask[1]}%;width:${a.mask[2]}%;height:${a.mask[3]}%"></span>`:''}</div>`:`<img src="${esc(a.path)}" width="${a.width}" height="${a.height}" loading="lazy" alt="${esc(label)}">`).join('')}</div>`;}
function answer(p){return `${p.answer.text?`<p class="answer-key">${esc(p.answer.text)}</p>`:''}${p.answer.assets?images(p.answer.assets,'Answer and working'):''}`;}
function helpSection(parts,body){return parts.map(p=>`<section class="help-section">${parts.length>1&&p.label?`<h3>Part ${esc(partLabel(p.label))}</h3>`:''}${body(p)}</section>`).join('');}
export function practiceCard(result,index,data){
 const {question:q,targets}=result,selected=new Set(targets.map(p=>p.label)),contexts=new Set(),supplied=new Set();let body='';
 for(const p of targets){for(const c of q.context.filter(c=>p.context_ids.includes(c.id))){if(!contexts.has(c.id)){body+=`<div class="part-context">${images(c.assets,'Information for this question',index===0)}</div>`;contexts.add(c.id);}}
 if(p.given)body+=`<div class="given-result"><strong>Use this result</strong><p>${esc(p.given)}</p></div>`;
 for(const r of p.requires||[]){if(!selected.has(r)&&!supplied.has(r)&&!p.given){const prior=q.parts.find(x=>x.label===r);if(prior){body+=`<div class="given-result"><strong>Use this result from part ${esc(partLabel(r))}</strong>${answer(prior)}</div>`;supplied.add(r);}}}
 body+=`<section class="focused-part">${targets.length>1&&p.label?`<div class="part-heading"><h3>Part ${esc(partLabel(p.label))}</h3>${p.marks?`<span class="part-marks">${p.marks} ${p.marks===1?'mark':'marks'}</span>`:''}</div>`:''}${images(p.assets,'Question'+(p.label?' part ('+p.label+')':''),index===0)}</section>`;}
 const id='practice-'+index,marks=targets.every(p=>p.marks)?targets.reduce((n,p)=>n+p.marks,0):null;
 const hints=helpSection(targets,p=>`<p>${esc(p.hint||data.guidance[p.guidance].hint)}</p>`),notes=helpSection(targets,p=>`<ul>${(p.notes||data.guidance[p.guidance].notes).map(n=>`<li>${esc(n)}</li>`).join('')}</ul>`),answers=helpSection(targets,answer);
 return `<article class="question-card" id="${id}" data-index="${index}"><header class="question-head"><h2>Practice question ${index+1}</h2>${marks?`<span class="question-marks">${marks} ${marks===1?'mark':'marks'}</span>`:''}</header>${body}<div class="help-actions"><div class="help-controls">${['Hint','Key notes','Answer'].map((n,i)=>`<button type="button" class="help-toggle" aria-expanded="false" aria-controls="${id}-help-${i}">${n}</button>`).join('')}</div>${[hints,notes,answers].map((html,i)=>`<div class="help-content ${i===2?'help-answer':''}" id="${id}-help-${i}" hidden><h3 class="help-title">${['Hint','Key notes','Answer'][i]}</h3>${html}</div>`).join('')}</div></article>`;
}
