import {assetUrl} from './asset-delivery.js';
import {icon} from './numeris.js';
import {revealItems,revealView,openReader,closeReader} from './motion.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let catalog,pending;
const ready=new Set();
async function data(){if(catalog)return catalog;pending??=fetch('./numeris-catalog.json').then(r=>{if(!r.ok)throw new Error('Catalog unavailable');return r.json();});catalog=await pending;return catalog;}
export async function show(page){if(ready.has(page))return;await data();if(ready.has(page))return;if(page==='notes')notes();else papers();ready.add(page);}
function notes(){
 const symbols=['☼','4πr²','α','Δα','ε','CO₂','λ','ΔT','σT⁴','⇄'];
 document.getElementById('notes-content').innerHTML=`<article class="lab-hero"><div class="lab-hero-text"><span class="n-tag light">B.2 &nbsp;·&nbsp; SL &amp; HL</span><p class="n-kicker">A PLANET IN BALANCE</p><h2>A little sunlight.<br>A world of physics.</h2><p>Follow the energy through Earth’s climate. Explore the greenhouse effect, one idea at a time.</p><div class="lab-actions"><a class="n-button white" href="learn/greenhouse-effect/">Start discovering <span aria-hidden="true">↗</span></a><span>10 units · Read, understand &amp; practise</span></div></div><div class="lab-orbit" aria-hidden="true"><div class="lab-rays"></div><div class="lab-planet"></div><span class="orbit-label l1">INCOMING ENERGY</span><span class="orbit-label l2">OUTGOING ENERGY</span><span class="orbit-equation">(1 − α)S / 4 = εσT⁴</span></div></article><div class="section-heading notes-heading"><div><h2>Your path through the greenhouse effect</h2><p>Follow the sequence or jump into an idea that interests you.</p></div><span class="n-tag">10 STUDY UNITS</span></div><div class="lesson-grid">${catalog.lessons.map((l,i)=>`<a class="lesson-tile" href="learn/greenhouse-effect/#${esc(l.id)}"><div class="lesson-tile-top"><span class="lesson-number">${String(i+1).padStart(2,'0')}</span><span class="lesson-symbol" aria-hidden="true">${symbols[i]}</span></div><h3>${esc(l.title)}</h3><p>${esc(l.goal)}</p><div class="lesson-tile-foot"><span>${l.readingMinutes} min read · ${l.sections} sections</span><span aria-hidden="true">↗</span></div></a>`).join('')}</div><div class="lab-next"><div><span class="n-kicker">TURN UNDERSTANDING INTO CONFIDENCE</span><h3>Ready to connect the ideas?</h3></div><a class="n-button" href="learn/greenhouse-effect/#combined">Combined exam practice <span aria-hidden="true">↗</span></a><a class="n-button blue" href="#choose?topic=B.2">B.2 topic questions <span aria-hidden="true">↗</span></a></div><footer class="n-footer"><span>The greenhouse-effect course is the current study-notes collection.</span><span>Stay curious.</span></footer>`;
}
function papers(){
 const years=[...new Set(catalog.papers.map(p=>p.year))].sort((a,b)=>b-a);
 document.getElementById('papers-content').innerHTML=`<div class="archive-intro"><div class="archive-emblem">${icon('paper')}</div><div><h2>The Exam Archive</h2><p>Settle in with a full paper. Open its mark scheme when you’re ready to review.</p></div><div class="archive-total"><strong>${catalog.papers.length}</strong><span>papers to explore</span></div></div><form class="archive-filters" id="paper-filters"><label>Level<select name="level"><option value="all">SL &amp; HL</option><option value="SL">Standard level</option><option value="HL">Higher level</option></select></label><label>Year<select name="year"><option value="all">All years</option>${years.map(y=>`<option value="${y}" ${y===2025?'selected':''}>${y}</option>`).join('')}</select></label><label>Paper<select name="paper"><option value="all">All papers</option>${['1A','1B','2','1','3'].map(p=>`<option value="${p}">Paper ${p}</option>`).join('')}</select></label><label>Session<select name="session"><option value="all">All sessions</option><option value="May">May</option><option value="November">November</option></select></label><button class="archive-reset" type="reset">Reset</button></form><div class="archive-results-bar"><p id="paper-count" role="status" aria-live="polite"></p><span>Newest first</span></div><div class="paper-grid" id="paper-grid"></div><button class="n-button archive-more" id="paper-more" type="button" hidden>Show more papers</button><p class="archive-note"><strong>Original papers · individual question review pending.</strong> Earlier-course papers may contain topics outside the current syllabus. For selected topic questions, use the <a href="#choose">Practice Studio</a>.</p><dialog class="paper-reader" id="paper-reader" aria-labelledby="reader-title"><div class="reader-header"><div><span class="n-kicker">THE EXAM ARCHIVE</span><h2 id="reader-title"></h2></div><button class="reader-close" type="button" aria-label="Close paper">×</button></div><div class="reader-toolbar"><div class="reader-tabs" role="group" aria-label="Choose document"><button type="button" id="reader-question" aria-pressed="true">Question paper</button><button type="button" id="reader-mark" aria-pressed="false">Mark scheme</button></div><a id="reader-open" class="n-link" target="_blank" rel="noopener">Open PDF ↗</a></div><iframe id="reader-frame" title="Physics exam paper"></iframe><p class="reader-note">If the PDF does not appear here, select Open PDF.</p></dialog>`;
 // All archive choices refer to local originals; no live external lookup is needed.
 const form=document.getElementById('paper-filters'),grid=document.getElementById('paper-grid'),more=document.getElementById('paper-more');
 let matches=[],shown=0;
 function render(reset=true){if(reset){const f=Object.fromEntries(new FormData(form));matches=catalog.papers.filter(p=>Object.entries(f).every(([k,v])=>v==='all'||String(p[k])===v));shown=0;grid.innerHTML='';}const slice=matches.slice(shown,shown+18);grid.insertAdjacentHTML('beforeend',slice.map(p=>`<article class="paper-tile"><div class="paper-tile-top"><span class="paper-year">${p.year}<small>${esc(p.session)}</small></span><span class="n-tag ${p.syllabus==='current'?'current-tag':''}">${p.syllabus==='current'?'CURRENT COURSE':'EARLIER COURSE'}</span></div><h3>Physics <span>${esc(p.level)}</span><br>Paper ${esc(p.paper)}</h3><p>${p.level==='HL'?'Higher level':'Standard level'} · ${p.timezone==='unspecified'?'Timezone not specified':esc(p.timezone)}${p.option?' · Option '+esc(p.option):''}</p><div class="paper-tile-foot"><button type="button" class="n-link" data-paper-id="${esc(p.id)}">Open paper <span aria-hidden="true">↗</span></button><span>${p.markUrl?'Mark scheme included':'No mark scheme'}</span></div></article>`).join(''));if(ready.has('papers'))revealItems(grid,shown);shown+=slice.length;more.hidden=shown>=matches.length;document.getElementById('paper-count').textContent=`${matches.length} ${matches.length===1?'paper':'papers'} · ${shown} shown`;if(!matches.length)grid.innerHTML='<div class="archive-empty"><span aria-hidden="true">⌕</span><h3>No papers match these choices.</h3><p>Try a different year, paper or session.</p><button type="button" class="n-button" id="paper-clear">Clear filters</button></div>';grid.querySelector('#paper-clear')?.addEventListener('click',()=>{for(const select of form.querySelectorAll('select'))select.value='all';render();});}
 form.addEventListener('change',()=>render());form.addEventListener('submit',e=>e.preventDefault());form.addEventListener('reset',()=>setTimeout(()=>render(),0));more.addEventListener('click',()=>render(false));render();
 const dialog=document.getElementById('paper-reader');let active,opener;
 function documentView(mark){const url=assetUrl(mark?active.markUrl:active.url);document.getElementById('reader-frame').src=url+'#view=FitH';document.getElementById('reader-frame').title=mark?'Physics mark scheme':'Physics question paper';document.getElementById('reader-open').href=url;document.getElementById('reader-question').setAttribute('aria-pressed',String(!mark));document.getElementById('reader-mark').setAttribute('aria-pressed',String(mark));if(dialog.open)revealView(document.getElementById('reader-frame'));}
 grid.addEventListener('click',e=>{const button=e.target.closest('[data-paper-id]');if(!button)return;opener=button;active=catalog.papers.find(p=>p.id===button.dataset.paperId);document.getElementById('reader-title').textContent=`${active.session} ${active.year} · Physics ${active.level} · Paper ${active.paper}${active.timezone==='unspecified'?'':' · '+active.timezone}`;document.getElementById('reader-mark').disabled=!active.markUrl;documentView(false);openReader(dialog,button);document.body.style.overflow='hidden';});
 document.getElementById('reader-question').addEventListener('click',()=>documentView(false));document.getElementById('reader-mark').addEventListener('click',()=>documentView(true));dialog.querySelector('.reader-close').addEventListener('click',()=>closeReader(dialog));dialog.addEventListener('cancel',event=>{event.preventDefault();closeReader(dialog);});dialog.addEventListener('close',()=>{document.getElementById('reader-frame').src='about:blank';document.body.style.overflow='';opener?.focus();});dialog.addEventListener('click',e=>{if(e.target===dialog){const rect=dialog.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)closeReader(dialog);}});window.addEventListener('hashchange',()=>{if(dialog.open)dialog.close();});
}
